version: '3'
services:
  sogocom:
    image: svelte-docker-node
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy-node
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sogocom.rule=Host(`sogocom-beta.guillian.net`)"
      - "traefik.http.routers.sogocom.entrypoints=http"
      - "traefik.http.routers.sogocom-secure.rule=Host(`sogocom-beta.guillian.net`)"
      - "traefik.http.routers.sogocom-secure.entrypoints=https"
      - "traefik.http.routers.sogocom-secure.tls=true"
      - "traefik.http.services.sogocom.loadbalancer.server.port=3000"
    volumes:
      - ./website-data/dev.db:/app/dev.db
networks:
  traefik-net:
   external: true
volumes:
  website-data: